parser/urls.py
from django.urls import path
from . import views

#FOR CORE APP
app_name = "parser"

urlpatterns = [
    path("", views.index, name = "index"),
    path("add/<str:title>/<str:content>", views.add, name = "add")
]

wikiParser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('parser.urls'))
]

parser/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=64)
    content = models.TextField()
    
    def __str__(self):
        return self.title

parser/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages

from .models import *

import wikipedia

def index(request):
    if request.method == "GET":
        search = request.GET.get("search")
        if search is not None:
            try:
                found = True
                relevant_page = wikipedia.page(search)
                title = relevant_page.original_title
                content = relevant_page.summary
                context = {"title": title, "content": content, "found":found}
            except wikipedia.DisambiguationError as e:
                found = False
                s = e.options
                context = {"arr": s, "found":found}
            return render(request, "parser/index.html", context)
    return render(request, "parser/index.html")

def add(request, title, content):
    if request.method == "POST":
        f = Post(title = title, content = content)
        if Post.objects.filter(title = title).exists(): 
            messages.error(request, "This post already exists in database")
        else:
            messages.success(request, "This post was succesfully added to a database!")
        f.save()
        return HttpResponseRedirect(reverse("parser:index"))

parser/templates/parser/index.html
{% extends 'parser/layout.html' %}

{% block body %}
{% if messages %}
    {% for i in messages %}
        {{i}}
    {% endfor %}
{% endif %}
    {% if found %}
        <h1>{{title}}</h1>
        <p>{{content}}</p>
        <form action="{% url 'parser:add' title content %}" method = "post">
            {% csrf_token %}
            <button type = "submit" class ="btn btn-primary">Add</button>
        </form>
    {% else %}
        <h2>Maybe you meant:</h2>
        <ul class="list-group">
        <li class="list-group-item active">Results</li>
        {% for i in arr %}
            <li class="list-group-item">{{i}}</li>
        {% endfor %}
        </ul>
    {% endif %}
{% endblock body %}

parser/templates/parser/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wiki Search</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <form class="d-flex" action = "{% url 'parser:index' %}" method = "get">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name = "search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {% block body %}{% endblock body %}
</body>
</html>